version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
      - postgres
  mongo:
    image: mongo
    ports:
      - "27107:27107"
  postgres:
    image: postgres:9.6.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass123
      - POSTGRES_DB=postgres
